enum class TypeGame {
    CENTENA,
    MILHAR,
    DEZENA,
    GRUPO,
    UNIDADE,
    DUQUE_DE_DEZENAS,
    DUQUE_DE_GRUPO,
    TERNO_DE_DEZENA,
    TERNO_DE_GRUPO,
    MILHAR_CENTENA,
    CENTENA_DEZENA,
    QUADRA_DE_GRUPO,
    QUINA_DE_GRUPO,
    DUPLA_DE_GRUPO,

    PASSE_SECO,
    PASSE_VIRADO,

    MILHAR_INVERTIDA,
    CENTENA_INVERTIDA,
    MILHAR_CENTENA_DEZENA,
    MILHAR_CENTENA_INVERTIDA,

    DUQUE_DE_GRUPO_COMBINADO,
    DUPLA_DE_GRUPO_COMBINADO,
    TERNO_DE_GRUPO_COMBINADO,
    QUADRA_DE_GRUPO_COMBINADO,
    QUINA_DE_GRUPO_COMBINADO,
    DUQUE_DE_DEZENAS_COMBINADO,
    TERNO_DE_DEZENAS_COMBINADO,

    DUQUE_DE_DEZENAS_COMBINADO_COM_REPETCAO,
    TERNO_DE_DEZENAS_COMBINADO_COM_REPETICAO,

    INVERTIDO_DUQUE_DE_DEZENA_COMBINADO,
    INVERTIDO_TERNO_DE_DEZENA_COMBINADO,

    MILHAR_INVERTIDA_COM_REPETICAO_ID,
    CENTENA_INVERTIDA_COM_REPETICAO_ID,

}